### ISSUE TITLE
Deleting bug / Quantity bug

### ISSUE THREAD

**Issue by MastaGooz** [xaukael/griddy#11] opened 2024-01-19 09:30 UTC
Hi again !

I found 2 bugs in the module.

1 - Deleting bug :

When you drag an item (from the right side bar) directly on the same item in the grid, then the item is deleted (not form the grid but from the system directly, it just disapear from the data). Also in the new stack, the quantity is "undefined".

Step one : drag the item
![image](https://github.com/xaukael/griddy/assets/149971487/67268aa5-fd9f-4c3c-9a01-c632503b5ee8)
Step two : item is deleted
![image](https://github.com/xaukael/griddy/assets/149971487/e5a5b9b5-e576-4bba-bd33-95f2fbe54a69)
I tested this bug, it happens in all systems.

2 - Quantity bug :

This bug is only happening with Custom System Builder.
When you drag an item directly from the right side bar into the inventory (actor sheet) or the grid, then when you try to put it with other items of the same kind (to stack them), the quantity calculation is wrong.

I think this is because in Custom System Builder, the quantity (and all variables) are stored as strings (I don't know why), so this happen :
I drag a sword (x1) in the grid from the side bar to the grid.
I drag a sword (x1) in the grid from the side bar to the grid a second time.
Then I drag one sword on the other to stack them.
Then the quantity is 11 instead of 2.
So my guess is that the js code is doing "1" + "1" = "11" as a string.

I think the solution would be to force the quantity to be a number before operating the calculation, with parseInt() ?
The bug does not happen when I get the item from the canvas using Item Pile (because Item Pile had some Custom System Builder patching).

**Comment by xaukael** [comment] 2024-01-19 14:55
I think I have this fixed in 1.0.20. If not, could you send me your CSB world so I can properly test without building a system?

**Comment by MastaGooz** [comment] 2024-01-19 16:01
It seems to work fine ! Thank you !

I'll run some deep testing on multiple systems later to see if I find anything, but for now everything works.

**Comment by MastaGooz** [comment] 2024-01-19 23:06
I found something else.
When the grid is overloaded, the objects blink strangely (the red outline does not appear).
Also, as long as the grid is open (while overloaded like this), I can't delete items from the sheet.

**Comment by xaukael** [comment] 2024-01-20 13:07
it should stop re-rendering when it cannot find a place for the first conflicting item it finds. If you find the cause for this not to be the case, let me know the specifics.

**Comment by xaukael** [comment] 2024-01-21 13:24
I found an error in my conflict resolution function that would, in certain circumstances, return a location for an item that was invalid. The circumstances were rather specific, which is why it seemed intermittent.

**Closed by xaukael** 2024-01-21 13:24 UTC
